version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: finance-api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "
      pnpm prisma generate &&
      pnpm prisma migrate dev &&
      pnpm prisma db seed &&
      pnpm run start:dev
    "

  db:
    image: postgres:16-alpine
    container_name: finance-postgres
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance
      POSTGRES_DB: finance
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
